version: '3.1'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0987654321
      MYSQL_DATABASE: tabby
      MYSQL_USER: joshua
      MYSQL_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
