version: '3.1'

services:
  backend:
    build: ./
    ports:
      - 7000:7000
    depends_on: 
      - mysql
  
  frontend:
    build: ./tab-front
    ports:
      - 8331:4300

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 0987654321
      MYSQL_DATABASE: tabby
      MYSQL_USER: joshua
      MYSQL_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3308:3306
  
networks: 
  backend:
    internal: true
  frontend:
    internal: true
  mysql:
    internal: true
